/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header_home";
import ProfileImage from "./ProfileImage";
import Footer from "./Footer";

function MyComponent() {
  return (
    <main className="flex overflow-hidden flex-col bg-neutral-100">
      <Header />
      <ProfileImage />
      <Footer />
    </main>
  );
}

export default MyComponent;
