/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Favorites() {
  return (
    <section className="flex flex-col items-center">
      <h2 className="mt-12 ml-7 text-4xl font-extrabold text-white max-md:mt-10">
        Tus Favoritos
      </h2>
      <p className="mt-5 ml-7 text-2xl text-center text-white max-md:max-w-full max-sm:pr-10 max-sm:pl-11 max-sm:-mr-0.5">
        Sabemos que el cambio de mood es muy importante, por esto para nosotros
        es muy importante
        <br />
        que conozcas tus favoritos del momento
      </p>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/7c3118c4a6e893607a14f120b69461de44c27020af3b4996595391ee7d73ecac?placeholderIfAbsent=true&apiKey=18c784e0a59f473995023f0319e731fa"
        alt="Favorites visualization"
        className="mt-10 ml-7 max-w-full aspect-[4.2] w-[882px] max-md:mt-10"
      />
    </section>
  );
}

export default Favorites;
