/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex flex-wrap gap-5 justify-between items-center px-16 pt-6 pb-9 mx-auto mt-48 w-full text-xs text-center text-white bg-black max-md:px-5 max-md:mt-10 max-md:max-w-full max-sm:pt-12">
      <p className="my-auto">
        Jhon Alejandro García Pareja
        <br />
        David Tovar Zurita
      </p>
      <p className="self-stretch my-auto">Proyecto de clase</p>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/0ff153322f312db0f814b78145bcceb441be0d29fc97ce36b63c3dee6cf29820?placeholderIfAbsent=true&apiKey=18c784e0a59f473995023f0319e731fa"
        alt="Project logo"
        className="object-contain shrink-0 self-stretch max-w-full aspect-[3.13] w-[200px] max-sm:mx-auto max-sm:w-full"
      />
    </footer>
  );
}

export default Footer;
