/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <header className="flex flex-wrap gap-10 py-px pr-5 pl-20 w-full text-base text-indigo-900 whitespace-nowrap bg-indigo-900 max-md:pl-5 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/4ef9abeb93c26e786aa1e21b897530320d828dc2090ca32a64176378c96d4988?placeholderIfAbsent=true&apiKey=18c784e0a59f473995023f0319e731fa"
        alt="Logo"
        className="object-contain aspect-[4.42] w-[345px] max-sm:w-[157px]"
      />
      <button className="px-7 py-3 my-auto rounded-2xl bg-zinc-300 max-md:px-5">
        Entrar
      </button>
    </header>
  );
}

export default Header;
