/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Hero() {
  return (
    <section className="flex relative flex-col justify-center items-center p-20 w-full text-white min-h-[262px] max-md:px-5 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/cc2821097b6940f5fcfad49ceef8ea6eb45a591f97c6f1218c5e6150e1857abe?placeholderIfAbsent=true&apiKey=18c784e0a59f473995023f0319e731fa"
        alt=""
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative flex-col max-w-full w-[940px]">
        <h1 className="text-4xl font-extrabold max-md:max-w-full">
          Explora la música que más escuchas conociendo tus estadísticas
        </h1>
        <p className="self-center mt-8 text-2xl max-md:max-w-full">
          Por medio de tu historial de Spotify podrás ver tu mundo musical.
        </p>
      </div>
    </section>
  );
}

export default Hero;
